#!perl
use v5.24.0;
use warnings;

use JSON::MaybeXS;
use LWP::UserAgent;
use MIME::Base64;

binmode *STDOUT, ':encoding(UTF-8)';

my $hostname   = $ENV{JMAP_HOSTNAME} // 'betajmap.fastmail.com';
my $username   = $ENV{JMAP_USERNAME} // die "no JMAP_USERNAME set!\n";
my $password   = $ENV{JMAP_PASSWORD} // die "no JMAP_PASSWORD set!\n";
my $auth_url   = "https://$hostname/.well-known/jmap";

my $auth_token = encode_base64("$username:$password", "");

my $www = LWP::UserAgent->new;
my $JSON = JSON::MaybeXS->new->utf8;

sub get_session {
  my $res = $www->get(
    $auth_url,
    Authorization  => "basic $auth_token",
  );

  return $JSON->decode($res->decoded_content);
}

my $session = get_session();

my $account_id = $session->{primaryAccounts}->{"urn:ietf:params:jmap:mail"};
my $api_url = $session->{apiUrl};

my $res = $www->post(
  $api_url,
  'Content-Type' => 'application/json',
  Authorization  => "basic $auth_token",
  Content => encode_json({
    using => [ "urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail" ],
    methodCalls => [
      [ 'Email/query',
        {
          accountId => $account_id,
          sort  =>  [ { property => "receivedAt", isAscending => \0 } ],
          limit => 10,
        },
        'a',
      ],
      [ 'Email/get',
        { accountId => $account_id,
          properties => [ 'id', 'subject', 'receivedAt' ],
          '#ids' => { resultOf => 'a', name => 'Email/query', path => '/ids/*' },
        },
        'b',
      ]
    ],
  }),
);

die $res->as_string unless $res->is_success;

for my $email (
  $JSON->decode($res->decoded_content)->{methodResponses}[1][1]{list}->@*
) {
  printf "%20s - %s\n", $email->{receivedAt}, $email->{subject};
}
